version: '3'
services:
  web:
    # Docker image (NAME:TAG)
    #   - image: ghcr.io/geowerkstatt/interlis-check-service:v1
    #     Stable tag for a specific major version
    #
    #   - image: ghcr.io/geowerkstatt/interlis-check-service:v1.2.3
    #     Stable tag for a specific version
    #
    #   - image: ghcr.io/geowerkstatt/interlis-check-service:latest
    #     Points to the latest stable tag, no matter what the current major version is
    #     May contain breaking changes and incompatibilities
    #     NOT RECOMMENDED!
    #
    #   - image: ghcr.io/geowerkstatt/interlis-check-service:edge
    #     Reflects the last commit of an active branch
    #     May contain breaking changes and incompatibilities
    #     NOT RECOMMENDED!
    #image: ghcr.io/geowerkstatt/interlis-check-service:edge
    build:
      context: .
      dockerfile: Dockerfile
      target: final
      args:
        - VERSION=0.1.100
        - REVISION=abcdefg
    # Docker container restart behavior
    restart: unless-stopped
    # Mount paths as volumes
    #
    # volumes:
    #   - /path/to/logs:/logs
    #     Application and error logs
    #
    #   - /path/to/uploads:/uploads
    #     XTF transfer files, ilivalidator and session logs
    #
    #   - /path/to/config:/config
    #     Config folder with TOML files to control validation
    volumes:
      - ./src/ILICheck.Web/Logs:/logs
      - ./src/ILICheck.Web/Uploads:/uploads
      - ./src/ILICheck.Web/Config:/config
    # Add environment variables
    #
    # environment:
    #   - PUID=1000
    #     Optional, Default user id 941
    #     Using PUID and PGID allows to map the container's internal user to a user on the
    #     host machine which prevents permisson issues when writing files to the mounted volume
    #
    #   - PGID=1000
    #     Optional, Default group id 941
    #     Using PUID and PGID allows to map the container's internal user to a user on the
    #     host machine which prevents permisson issues when writing files to the mounted volume
    #
    #   - ILIVALIDATOR_VERSION=1.11.10
    #     Optional, Default latest version available from
    #     https://www.interlis.ch/downloads/ilivalidator
    #
    #   - ILIVALIDATOR_CONFIG_NAME=Beispiel1.TOML
    #     Optional TOML config file name in mounted /config volume
    #
    #   - ILIVALIDATOR_ENABLE_TRACE=true
    #     Optional, Enable validation trace messages, Default false
    #
    #   - ILIVALIDATOR_MODEL_DIR=https://models.example.com;http://models.interlis.ch/
    #     Optional semicolon-separated list of repositories with ili-files
    #     Default http://models.interlis.ch/
    #
    #   - PROXY=http://USER:PASSWORD@example.com:8080
    #     Optional, Configuring proxy settings for all apps in the container
    #     Protocol (e.g. http://) and port (e.g. 8080) is mandatory in order do be able
    #     to parse values for ilivalidator properly
    #     examples: - http://example.com:8080
    #               - https://host.example.com:443
    #               - http://10.10.5.68:5698
    #               - https://USER:PASSWORD@10.10.5.68:8443
    #
    #   - NO_PROXY=host.example.com,10.1.0.0/16
    #     Optional, Specifies URLs that should be excluded from proxying
    environment:
      - PUID=1000
      - PGID=1000
    # Expose ports (HOST:CONTAINER)
    #
    # ports:
    #   - 3080:80
    #     Map port 80 in the container to any desired port on the Docker host
    #     INTERLIS Web-Check-Service web app runs on port 80 inside the container
    ports:
      - 3080:80
