name: Beta

on:
  push:
    branches:
      - 'releases/beta/**'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  create-beta:
    runs-on: ubuntu-latest
    name: Build and push Docker image

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set environment variables
        run: |
          echo VERSION=$(cat VERSION).$GITHUB_RUN_NUMBER-beta >> $GITHUB_ENV
          echo IMAGE_NAME=$REGISTRY/$(echo ${GITHUB_REPOSITORY,,}) >> $GITHUB_ENV
          echo COMMITED_AT=$(git show -s --format=%cI `git rev-parse HEAD`) >> $GITHUB_ENV
          echo REVISION=$(git rev-parse --short HEAD) >> $GITHUB_ENV
          echo DOCKER_BETA_TAG=$(echo ${GITHUB_REF##*/}-beta) >> $GITHUB_ENV

      - name: Collect Docker image metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMAGE_NAME }}
          labels: |
            org.opencontainers.image.created=${{ env.COMMITED_AT }}
            org.opencontainers.image.version=v${{ env.VERSION }}
            org.opencontainers.image.maintainer=GeoWerkstatt GmbH <support@geowerkstatt.ch>
          tags: |
            type=raw,value=${{ env.DOCKER_BETA_TAG }}

      - name: Log in to the GitHub container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner  }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          build-args: |
            VERSION=${{ env.VERSION }}
            REVISION=${{ env.REVISION }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:${{ env.DOCKER_BETA_TAG }}
          cache-to: type=inline
