name: Ci

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Run dotnet build and test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0'

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build

      - name: Test
        run: dotnet test
